spring:
  application:
    name: 'takeaway-coding-challenge'
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
  liquibase:
    change-log: config/liquibase/master.xml
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
logbook:
  predicate:
    include:
      - path: '**'
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
logging:
  level:
    root: INFO
scheduled:
  employees-clean-job: 10000
  outbox: 1000
messaging:
  queue-name: 'employees-queue'
  external-in:
    contract:
      queue: 'contract-queue'
